### ISSUE TITLE
package is not 'exactly' like Bluebird's Promise.map

### ISSUE THREAD

**Issue by bjrmatos** [yoshuawuyts/promise-map#2]
shouldn't this [line](https://github.com/yoshuawuyts/promise-map/blob/master/index.js#L14) be `return Promise.all(val.map(fn, ctx))` ? if you only do `Promise.resolve` and in the `map` function you return another promise (or promises chain) the resolved array doesn't have the final resolved values.

i have experienced this behaviour and changing `Promise.resolve` to `Promise.all` resolves the issue.

**Comment by yoshuawuyts** [comment]
Oh yeah it should; PR welcome!
